[package]
name = "KLPhash"
version = "0.1.3"
authors = ["Keenan Lidral-Porter <keenan@surfair.com>"]

description = "small hashing fn library - str -> u32"
keywords = ["hash", "hashing", "function"]
repository = "https://github.com/kayellpeee/KLPhash"
license = "MIT"
